### ISSUE TITLE
Connection timeout error in ProfiMail email client

### ISSUE THREAD

**Issue by artem78** [shinovon/newtls#3]
Hello, this is me again with another trouble using Profimail client with newtls.

I'm not sure this related with your library, but I didn't have any problems before install it.

Often (but not always) fetching new mails failed with connection timeout error. I use two mailboxes providered with yandex.ru and mail.ru, but this problem occurs only with second one.

From log:

> TimerExpired
> Error: -33 (Time out)
> Destroying socket
> SSLsock close: OK

Full logs:

[ProfiMailLog 1.txt](https://github.com/user-attachments/files/19407931/ProfiMailLog.1.txt)
[ProfiMailLog 2.txt](https://github.com/user-attachments/files/19407932/ProfiMailLog.2.txt)

In addition sometimes (also using profimail) phone goes to reboot.

-----------------------------------
**Phone:** Nokia N95 8GB
**Platform:** s60v3.1 Symbian 9.2
**Firmware:** v35.0.001 (latest)

**Comment by artem78** [comment]
And what about time out error?

**Comment by artem78** [comment]
Possible another way to reproduce this problem. Try to open in system browser url https://e.mail.ru. On my phone loading freezes on infinite time without any error and with 0 bytes recieved.

Could you please check this? Many other sites/mailboxes works, but I can't understand what is wrong with mail.ru?

**Comment by artem78** [comment]
In sources i see you have logging for debug build. It would be great if I 
can see what happens in log file. Could you please build SIS package with 
logging enabled?

I tried to open project in Carbide ide, but failed to import due to 
cproject file missed.

**Comment by shinovon** [comment]
[ssl.zip](https://github.com/user-attachments/files/19566308/ssl.zip)
Place commsdbg.ini in C:\Logs\

**Comment by shinovon** [comment]
Not sure if 9.2 supports comsdbgutil api.

**Comment by artem78** [comment]
Seems not works.

> #Logging started on 03/04/2025. Output version 2
> #Bad media setting in ini file.
> #There is a problem with the ini file
> #Time = 13:47:01
> #Time = 13:47:02
> #Time = 13:47:03
> #Time = 13:47:04
> #Time = 13:47:05

**Comment by shinovon** [comment]
Sorry, there was a mistake in commsdbg.ini

Replace `MEDIAFILE` to `MEDIA FILE`

**Comment by artem78** [comment]
Fixed, but no additional info was added to log file.

**Comment by artem78** [comment]
Any ideas?

**Comment by artem78** [comment]
Also I could try to run it in Carbide ide debugger, but project import failed due to missed .cproject file in repository.

**Comment by shinovon** [comment]
> but project import failed due to missed .cproject file in repository.

I think it is better to create new project instead, I didn't think about building instructions for this project at all.

**Comment by artem78** [comment]
> cannot find include file: 'comms-infras/commsdebugutility.mmh' at \newtls\group\newtls.mmp:9

**Comment by shinovon** [comment]
Use Nokia_Symbian3_SDK_v1.0

**Comment by artem78** [comment]
Could you please give download link? I can't find it.

**Comment by shinovon** [comment]
https://archive.org/download/nokia_sdks_n_dev_tools

**Comment by artem78** [comment]
There's no Symbian3 SDK.

**Comment by artem78** [comment]
With Symbian3 SDK build process provide many strange errors.

![Image](https://github.com/user-attachments/assets/6ff9ac6a-0d0c-48fd-8689-18bc6120dac8)

I tried to use Carbide v2.7 and 3.2. Very hard to understand without any instruction and with insufficient skills.


> Not sure if 9.2 supports comsdbgutil api.

Could you please remake logging without using it and rebuild sis? Like directly write to file with RFile::Write().

**Comment by artem78** [comment]
Although I'm not specialist, I was able to get more details about initial timeout issue. Hope this will help to understand what is going wrong.


I run test mail server. It configured for support tls1.2 and connection without encryption. I discovered that timeout error occurs when client tries to get mails from big folder (several hundred letters or more). Maybe problem with big packets or when data splits to chunks?

I reproduced the problem, captured traffic with wireshark and encrypted it.

Connection always interrupted after selected with green color packet.

![Image](https://github.com/user-attachments/assets/480415f5-95b8-46a1-b1c1-a2a76b7154a2)

After 30s client establishes a new connection.

Wireshark dump file: [traffic_with_tls_2.cap.zip](https://github.com/user-attachments/files/19733956/traffic_with_tls_2.cap.zip)
Private RSA key (for encrypt dump): [ssl-cert-snakeoil.key.zip](https://github.com/user-attachments/files/19733989/ssl-cert-snakeoil.key.zip)


Then just for comparision I make the same test, but with **disabled** tls.

![Image](https://github.com/user-attachments/assets/75cbbe43-d9fc-41d0-a47b-04a3a6119538)

No errors, command execution continues further.

Dump without tls: [traffic_without_tls_2.cap.zip](https://github.com/user-attachments/files/19734063/traffic_without_tls_2.cap.zip)

**Comment by shinovon** [comment]
Before resolving issue #1, I had similar problem with TLS in Java, after receiving some amount of data, it started to corrupt. Was fixed by reprogramming how asynchronous event flow works.

I will return to this later

**Comment by artem78** [comment]
Ok, I'll be waiting.

**Comment by shinovon** [comment]
Fixed log config, seems to be working on 9.2

[commsdbg.zip](https://github.com/user-attachments/files/19823066/commsdbg.zip)

**Comment by artem78** [comment]
Thanks, logging works.

**Comment by artem78** [comment]
I recorded log:

[log.zip](https://github.com/user-attachments/files/19825379/log.zip)

**Comment by shinovon** [comment]
[udeb.zip](https://github.com/user-attachments/files/19825963/udeb.zip)
check this

**Comment by artem78** [comment]
Works better, but sometimes timeout error still happens. I will better check later.

**Comment by artem78** [comment]
Hi. Sorry, was no time to write earlier. Is this project is still alive?

I checked better your patch, but unfortunatelly it didn't fix initial problem.

**Comment by shinovon** [comment]
[udeb.zip](https://github.com/user-attachments/files/22086555/udeb.zip)
Last commit replaces `Recv` to `RecvOneOrMore`, this may help with the timeout issue.
Before applying, make sure latest version of mbedtls.sis is installed

**Comment by shinovon** [comment]
In that case, I don't know if I can solve this.

**Comment by shinovon** [comment]
Trying to reproduce this in Symbian^3 SDK emulator, it just loads instantly.

**Comment by artem78** [comment]
Just tested on Symbain^3 - no problems.

**Comment by shinovon** [comment]
> With Symbian3 SDK build process provide many strange errors.

Now after 5718722650c759d148eb95ac3e476428f95ea223, it should be possible to compile this project with out-of-box Symbian SDK without modifications.
